monocongo/cvdata

.gitignore, cvdata/openimages.py, setup.py
Using the current `setup.py` results in no issues when uploading to the PyPI test repository:
```
$ python setup.py sdist bdist_wheel
running sdist
running egg_info
writing cvdata.egg-info/PKG-INFO
writing dependency_links to cvdata.egg-info/dependency_links.txt
writing requirements to cvdata.egg-info/requires.txt
writing top-level names to cvdata.egg-info/top_level.txt
reading manifest file 'cvdata.egg-info/SOURCES.txt'
writing manifest file 'cvdata.egg-info/SOURCES.txt'
running check
creating cvdata-0.0.1
creating cvdata-0.0.1/cvdata
creating cvdata-0.0.1/cvdata.egg-info
copying files to cvdata-0.0.1...
copying README.md -> cvdata-0.0.1
copying setup.py -> cvdata-0.0.1
copying cvdata/__init__.py -> cvdata-0.0.1/cvdata
copying cvdata/openimages.py -> cvdata-0.0.1/cvdata
copying …
```
=> New setup.py file suficient for PyPI

cvdata/resize.py, cvdata/utils.py
initial version of script/module for resizing images and corresponding annotations
Resolves issue #2
=> Resize script/module

README.md, cvdata/visualize.py
=> Visualization script/module for COCO, Darknet, KITT, and PASCAL VOC

tests/assert_utils.py, tests/test_relabel.py, tests/test_resize.py, tests/test_resize/image.xml, tests/test_resize/image_w240_h720.xml
moved testing assertion functions into a separate utils module, updated the resize test PASCAL files, testing the updates of PASCAL and KITTI files
related to issue #2
=> Additional tests for resize

cvdata/openimages.py
added a directory option for storage of CSV files used for storing and loading for annotations and class descriptions
Resolves issue #12
=> CSV directory option for caching CSV files

cvdata/convert.py, cvdata/openimages.py, cvdata/split.py, setup.py, tests/test_relabel.py, tests/test_resize.py
Conversions included:
1. PASCAL to KITTI
2. PASCAL to OpenImages
Resolves issues #3 and #21
=> Annotation conversions

cvdata/visualize.py
added support for visualization of images with OpenImages CSV annotations
Resolves issue #24
=> Visualization of images with OpenImages CSV annotations

cvdata/common.py, cvdata/exclude.py, cvdata/openimages.py, cvdata/relabel.py, cvdata/resize.py, cvdata/split.py, cvdata/visualize.py, tests/test_exclude.py, tests/test_exclude/exclusions.txt, tests/test_exclude/openimages/openimages.csv, tests/test_relabel.py, tests/test_resize.py
Added an exclusion module to facilitate removal of files from a dataset based on a list of file IDs.
Resolves issue #27
=> Exclusion module

README.md, cvdata/split.py
=> Splitter module and CLI updates

README.md, cvdata/convert.py, cvdata/split.py
=> Enable images-only splits

README.md, cvdata/convert.py
=> New CLI option for PNG to JPG conversion

README.md, cvdata/rename.py
=> Module with CLI for renaming image files

README.md, cvdata/__init__.py, setup.py
Updated to version 0.0.3
Resolves issue #60
=> Version update

README.md, cvdata/clean.py
=> Sanitization for Darknet datasets

README.md, cvdata/openimages.py
Added an option for limiting the maximum number of images to download.
Resolves issue #69
=> New --limit CLI argument for openimages

README.md, cvdata/clean.py
=> Added option to remove labels from annotation files

cvdata/convert.py, cvdata/visualize.py
Support for KITTI to Darknet conversion, with attendant updates to the visualization code for Darknet datasets.
Resolves issue #79
=> KITTI to Darknet conversion

cvdata/clean.py
=> Fixed Darknet bbox cleaning bug

cvdata/clean.py, cvdata/filter.py, cvdata/rename.py
New module with CLI for filtering datasets to a subset of files with a specified number of boxes per class.
Resolves issue #93
=> Filter module

README.md, cvdata/filter.py
=> Small cleanups and additonal documentation for the filter module

README.md, cvdata/mask.py, setup.py
=> New module/CLI to create segmentation masks from VIA JSON

cvdata/__init__.py, setup.py
Now available on [PyPI](https://pypi.org/project/cvdata/)
Resolves issue #106
=> Updated version number to 0.0.5

README.md, cvdata/mask.py
=> New option for single mask files

cvdata/mask.py, cvdata/resize.py, cvdata/visualize.py
=> Now possible to create and visualize TFRecords containing segmentation masks

cvdata/mask.py, cvdata/utils.py, cvdata/visualize.py
Addresses issues #111 and #112
=> Updates for more efficient (DeepLab v3 format) segmentation TFRecords

README.md, cvdata/__init__.py, cvdata/mask.py, setup.py
Also a new version number, 0.0.6
Resolves issues #116 and #117
=> Now able to specify a split when creating segmentation (mask) TFRecords

.github/workflows/continuous-integration-workflow.yml
=> Additional PR for testing caching for dependencies

src/cvdata/clean.py, tests/test_clean.py
Adds a functionality to the clean script for keeping only some labels, it is very similar to remove_labels.
=> adds label keep funcionality
